#!/bin/bash

cd /opt/solr/server

exec java -server \
    $JAVA_ARGS \
    -XX:NewRatio=3 \
    -XX:SurvivorRatio=4 \
    -XX:TargetSurvivorRatio=90 \
    -XX:MaxTenuringThreshold=8 \
    -XX:+UseConcMarkSweepGC \
    -XX:ConcGCThreads=4 \
    -XX:ParallelGCThreads=4 \
    -XX:+CMSScavengeBeforeRemark \
    -XX:PretenureSizeThreshold=64m \
    -XX:+UseCMSInitiatingOccupancyOnly \
    -XX:CMSInitiatingOccupancyFraction=50 \
    -XX:CMSMaxAbortablePrecleanTime=6000 \
    -XX:+CMSParallelRemarkEnabled \
    -Djetty.port=$SOLR_PORT \
    -DSTOP.PORT=8703 \
    -DSTOP.KEY=solrrocks \
    -Duser.timezone=UTC \
    -Djetty.home=/opt/solr/server \
    -Dsolr.solr.home=/opt/solr/data \
    -Dsolr.data.home=/opt/solr/data/cores \
    -Dsolr.install.dir=/opt/solr \
    -Dsolr.default.confdir=/opt/solr/server/solr/configsets/_default/conf \
    -Dsolr.autoSoftCommit.maxTime=3000 \
    -Dsolr.clustering.enabled=true \
    -Dsolr.disable.shardsWhitelist=true \
    -Xss256k \
    -Dlog4j.configurationFile=/opt/solr/server/resources/log4j2-console.xml \
    -Dsolr.httpclient.builder.factory=org.apache.solr.client.solrj.impl.PreemptiveBasicAuthClientBuilderFactory \
    -jar /opt/solr/server/start.jar \
    --module=http