name: Build and Publish

on:
  push:
    branches: [master]
  pull_request:

jobs:
  build-and-push-docker-image:
    name: Build image and push to Docker Hub
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build image and push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: .
          tags: |
            opcycle/solr:8.2
          push: ${{ github.ref == 'refs/heads/master' }}
          build-args: SOLR_VERSION=8.2.0
      
      - name: Build image and push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: .
          tags: |
            opcycle/solr:8.3 
          push: ${{ github.ref == 'refs/heads/master' }}
          build-args: SOLR_VERSION=8.3.1

      - name: Build image and push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: .
          tags: |
            opcycle/solr:8.4
          push: ${{ github.ref == 'refs/heads/master' }}
          build-args: SOLR_VERSION=8.4.1

      - name: Build image and push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: .
          tags: |
            opcycle/solr:8.5
          push: ${{ github.ref == 'refs/heads/master' }}
          build-args: SOLR_VERSION=8.5.2

      - name: Build image and push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: .
          tags: |
            opcycle/solr:8.6
          push: ${{ github.ref == 'refs/heads/master' }}
          build-args: SOLR_VERSION=8.6.3

      - name: Build image and push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: .
          tags: |
            opcycle/solr:8.7
          push: ${{ github.ref == 'refs/heads/master' }}
          build-args: SOLR_VERSION=8.7.0

      - name: Build image and push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: .
          tags: |
            opcycle/solr:8.8
          push: ${{ github.ref == 'refs/heads/master' }}
          build-args: SOLR_VERSION=8.8.2

      - name: Build image and push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: .
          tags: |
            opcycle/solr:8.9
          push: ${{ github.ref == 'refs/heads/master' }}
          build-args: SOLR_VERSION=8.9.0

      - name: Build image and push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: .
          tags: |
            opcycle/solr:8.10
          push: ${{ github.ref == 'refs/heads/master' }}
          build-args: SOLR_VERSION=8.10.0